spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE.ENDPOINT_URL.dev}:5432/soft?currentSchema=${DATABASE.NAME.dev}
    username: ${DATABASE.USERNAME.dev}
    password: ${DATABASE.PASSWORD.dev}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
